Repository redacademy/bikelocker-spring-2019, pull requests merged in 2019-06, with the labels that each got.

#36 move react-native files to client folder
  README.md
  __tests__/App-test.js
  client/.buckconfig
  client/.flowconfig
  client/.gitattributes
  client/.watchmanconfig
  client/App.js
  client/__tests__/App-test.js
  client/android/app/BUCK
  client/android/app/build.gradle
  client/android/app/build_defs.bzl
  client/android/app/proguard-rules.pro
  client/android/app/src/debug/AndroidManifest.xml
  client/android/app/src/main/AndroidManifest.xml
  client/android/app/src/main/java/com/bikelockerspring2019/MainActivity.java
  client/android/app/src/main/java/com/bikelockerspring2019/MainApplication.java
  client/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  client/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  client/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  client/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  client/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  client/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  client/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  client/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  client/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  client/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  client/android/app/src/main/res/values/strings.xml
  client/android/app/src/main/res/values/styles.xml
  client/android/build.gradle
  client/android/gradle.properties
  client/android/gradle/wrapper/gradle-wrapper.jar
  client/android/gradle/wrapper/gradle-wrapper.properties
  client/android/gradlew
  client/android/gradlew.bat
  client/android/keystores/BUCK
  client/android/keystores/debug.keystore.properties
  client/android/settings.gradle
  client/app.json
  client/babel.config.js
  client/index.js
  client/ios/bikelockerSpring2019-tvOS/Info.plist
  client/ios/bikelockerSpring2019-tvOSTests/Info.plist
  client/ios/bikelockerSpring2019.xcodeproj/project.pbxproj
  client/ios/bikelockerSpring2019.xcodeproj/xcshareddata/xcschemes/bikelockerSpring2019-tvOS.xcscheme
  client/ios/bikelockerSpring2019.xcodeproj/xcshareddata/xcschemes/bikelockerSpring2019.xcscheme
  client/ios/bikelockerSpring2019/AppDelegate.h
  client/ios/bikelockerSpring2019/AppDelegate.m
  client/ios/bikelockerSpring2019/Base.lproj/LaunchScreen.xib
  client/ios/bikelockerSpring2019/Images.xcassets/AppIcon.appiconset/Contents.json
  client/ios/bikelockerSpring2019/Images.xcassets/Contents.json
  client/ios/bikelockerSpring2019/Info.plist
  client/ios/bikelockerSpring2019/main.m
  client/ios/bikelockerSpring2019Tests/Info.plist
  client/ios/bikelockerSpring2019Tests/bikelockerSpring2019Tests.m
  client/metro.config.js
  client/package.json
  client/yarn.lock
Labels: organization

#35 init graphcool server
  client/android/app/build.gradle
  client/android/app/src/main/java/com/bikelockerspring2019/MainApplication.java
  client/android/settings.gradle
  client/ios/bikelockerSpring2019.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
  server/graphcool.yml
  server/package.json
  server/src/hello.graphql
  server/src/hello.js
  server/types.graphql
Labels: enhancement

#34 add project file structure
  js/App.js
  js/components/MapView/MapView.js
  js/components/MapView/index.js
  js/components/MapView/styles.js
  js/components/Search/Search.js
  js/components/Search/index.js
  js/components/Search/styles.js
  js/config/api.js
  js/config/globalStyles.js
  js/screens/About/About.js
  js/screens/About/AboutContainer.js
  js/screens/About/index.js
  js/screens/About/styles.js
  js/screens/AddSpot/AddSpot.js
  js/screens/AddSpot/AddSpotContainer.js
  js/screens/AddSpot/index.js
  js/screens/AddSpot/styles.js
  js/screens/Authentication/Authentication.js
  js/screens/Authentication/AuthenticationContainer.js
  js/screens/Authentication/index.js
  js/screens/Authentication/styles.js
  js/screens/Contact/Contact.js
  js/screens/Contact/ContactContainer.js
  js/screens/Contact/index.js
  js/screens/Contact/styles.js
  js/screens/FindSpot/FindSpot.js
  js/screens/FindSpot/FindSpotContainer.js
  js/screens/FindSpot/index.js
  js/screens/FindSpot/styles.js
  js/screens/HowToUseApp/HowToUseApp.js
  js/screens/HowToUseApp/HowToUseAppContainer.js
  js/screens/HowToUseApp/index.js
  js/screens/HowToUseApp/styles.js
  js/screens/Onboarding/Onboarding.js
  js/screens/Onboarding/OnboardingContainer.js
  js/screens/Onboarding/index.js
  js/screens/Onboarding/styles.js
  js/screens/Profile/Profile.js
  js/screens/Profile/ProfileContainer.js
  js/screens/Profile/index.js
  js/screens/Profile/styles.js
  js/screens/Resources/Resources.js
  js/screens/Resources/ResourcesContainer.js
  js/screens/Resources/index.js
  js/screens/Resources/styles.js
  js/screens/Reviews/Reviews.js
  js/screens/Reviews/ReviewsContainer.js
  js/screens/Reviews/index.js
  js/screens/Reviews/styles.js
  js/screens/Spot/Spot.js
  js/screens/Spot/SpotContainer.js
  js/screens/Spot/index.js
  js/screens/Spot/styles.js
Labels: enhancement

#37 move js folder into client folder
  client/js/App.js
  client/js/components/MapView/MapView.js
  client/js/components/MapView/index.js
  client/js/components/MapView/styles.js
  client/js/components/Search/Search.js
  client/js/components/Search/index.js
  client/js/components/Search/styles.js
  client/js/config/api.js
  client/js/config/globalStyles.js
  client/js/navigation/config.js
  client/js/screens/About/About.js
  client/js/screens/About/AboutContainer.js
  client/js/screens/About/index.js
  client/js/screens/About/styles.js
  client/js/screens/AddSpot/AddSpot.js
  client/js/screens/AddSpot/AddSpotContainer.js
  client/js/screens/AddSpot/index.js
  client/js/screens/AddSpot/styles.js
  client/js/screens/Authentication/Authentication.js
  client/js/screens/Authentication/AuthenticationContainer.js
  client/js/screens/Authentication/index.js
  client/js/screens/Authentication/styles.js
  client/js/screens/Contact/Contact.js
  client/js/screens/Contact/ContactContainer.js
  client/js/screens/Contact/index.js
  client/js/screens/Contact/styles.js
  client/js/screens/FindSpot/FindSpot.js
  client/js/screens/FindSpot/FindSpotContainer.js
  client/js/screens/FindSpot/index.js
  client/js/screens/FindSpot/styles.js
  client/js/screens/HowToUseApp/HowToUseApp.js
  client/js/screens/HowToUseApp/HowToUseAppContainer.js
  client/js/screens/HowToUseApp/index.js
  client/js/screens/HowToUseApp/styles.js
  client/js/screens/Onboarding/Onboarding.js
  client/js/screens/Onboarding/OnboardingContainer.js
  client/js/screens/Onboarding/index.js
  client/js/screens/Onboarding/styles.js
  client/js/screens/Profile/Profile.js
  client/js/screens/Profile/ProfileContainer.js
  client/js/screens/Profile/index.js
  client/js/screens/Profile/styles.js
  client/js/screens/Resources/Resources.js
  client/js/screens/Resources/ResourcesContainer.js
  client/js/screens/Resources/index.js
  client/js/screens/Resources/styles.js
  client/js/screens/Reviews/Reviews.js
  client/js/screens/Reviews/ReviewsContainer.js
  client/js/screens/Reviews/index.js
  client/js/screens/Reviews/styles.js
  client/js/screens/Spot/Spot.js
  client/js/screens/Spot/SpotContainer.js
  client/js/screens/Spot/index.js
  client/js/screens/Spot/styles.js
Labels: organization

#38 Ja feature global theme
  client/js/config/globalStyles.js
Labels: enhancement

#39 define schema for data models
  server/types.graphql
Labels: enhancement

#41 Js project dependencies
  client/android/app/build.gradle
  client/android/app/src/main/assets/fonts/AntDesign.ttf
  client/android/app/src/main/assets/fonts/Entypo.ttf
  client/android/app/src/main/assets/fonts/EvilIcons.ttf
  client/android/app/src/main/assets/fonts/Feather.ttf
  client/android/app/src/main/assets/fonts/FontAwesome.ttf
  client/android/app/src/main/assets/fonts/FontAwesome5_Brands.ttf
  client/android/app/src/main/assets/fonts/FontAwesome5_Regular.ttf
  client/android/app/src/main/assets/fonts/FontAwesome5_Solid.ttf
  client/android/app/src/main/assets/fonts/Foundation.ttf
  client/android/app/src/main/assets/fonts/Ionicons.ttf
  client/android/app/src/main/assets/fonts/MaterialCommunityIcons.ttf
  client/android/app/src/main/assets/fonts/MaterialIcons.ttf
  client/android/app/src/main/assets/fonts/Octicons.ttf
  client/android/app/src/main/assets/fonts/SimpleLineIcons.ttf
  client/android/app/src/main/assets/fonts/Zocial.ttf
  client/android/app/src/main/java/com/bikelockerspring2019/MainApplication.java
  client/android/settings.gradle
  client/ios/bikelockerSpring2019.xcodeproj/project.pbxproj
  client/ios/bikelockerSpring2019/Info.plist
  client/package.json
  client/yarn.lock
Labels: enhancement

#44 Added proper map places api
  client/android/app/build.gradle
  client/android/app/src/main/java/com/bikelockerspring2019/MainApplication.java
  client/android/settings.gradle
  client/ios/bikelockerSpring2019.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
  server/graphcool.yml
  server/package.json
  server/src/email-password/authenticate.graphql
  server/src/email-password/authenticate.ts
  server/src/email-password/loggedInUser.graphql
  server/src/email-password/loggedInUser.ts
  server/src/email-password/signup.graphql
  server/src/email-password/signup.ts
  server/src/hello.graphql
  server/src/hello.js
  server/types.graphql
  server/yarn.lock
Labels: enhancement

#42 change naming convetion
  client/js/App.js
  client/js/navigation/NavigationLayout.js
  client/js/navigation/RootStackNavigator.js
  client/js/screens/AddLocker/AddLocker.js
  client/js/screens/AddLocker/AddLockerContainer.js
  client/js/screens/AddLocker/index.js
  client/js/screens/AddLocker/styles.js
  client/js/screens/AddSpot/index.js
  client/js/screens/FindLocker/FindLocker.js
  client/js/screens/FindLocker/FindLockerContainer.js
  client/js/screens/FindLocker/index.js
  client/js/screens/FindLocker/styles.js
  client/js/screens/FindSpot/index.js
  client/js/screens/Locker/Locker.js
  client/js/screens/Locker/LockerContainer.js
  client/js/screens/Locker/index.js
  client/js/screens/Locker/styles.js
  client/js/screens/Spot/index.js
Labels: organization

#46 Js project dependencies
  server/package.json
  server/yarn.lock
Labels: enhancement

#50 Dependencies
  .gitignore
  client/ios/bikelockerSpring2019.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
Labels: enhancement

#51 Js project dependencies
  .gitignore
  client/ios/bikelockerSpring2019.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
Labels: enhancement

#55 Js project dependencies
  client/package.json
  client/yarn.lock
Labels: enhancement

#56 Js project dependencies
  client/android/app/build.gradle
  client/android/app/src/main/java/com/bikelockerspring2019/MainApplication.java
  client/android/settings.gradle
  client/ios/bikelockerSpring2019.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
  server/package.json
  server/yarn.lock
Labels: enhancement

#66 styled locator button and fixed issue with keyboard on search
  client/js/components/GoogleMapSearch/GoogleMapsSearch.js
  client/js/components/GoogleMapSearch/styles.js
  client/js/components/MapView/MapView.js
  client/js/components/MapView/styles.js
  client/js/navigation/config.js
Labels: enhancement

#60 Nc feature locker modal
  client/ios/Podfile.lock
  client/ios/bikelockerSpring2019.xcodeproj/project.pbxproj
  client/js/App.js
  client/js/assets/icons/actions/floatingbackbutton.png
  client/js/assets/icons/addspotv3.png
  client/js/assets/icons/appheader/hamburgermenu.png
  client/js/assets/icons/appheader/location.png
  client/js/assets/icons/bikelocker/combinedlogo/horizontal/black.png
  client/js/assets/icons/bikelocker/combinedlogo/horizontal/darkgreen.png
  client/js/assets/icons/bikelocker/combinedlogo/horizontal/darkgrey.png
  client/js/assets/icons/bikelocker/combinedlogo/horizontal/mediumgreen.png
  client/js/assets/icons/bikelocker/combinedlogo/horizontal/white.png
  client/js/assets/icons/bikelocker/combinedlogo/vertical/black.png
  client/js/assets/icons/bikelocker/combinedlogo/vertical/darkgreen.png
  client/js/assets/icons/bikelocker/combinedlogo/vertical/darkgrey.png
  client/js/assets/icons/bikelocker/combinedlogo/vertical/mediumgreen.png
  client/js/assets/icons/bikelocker/combinedlogo/vertical/white.png
  client/js/assets/icons/bikelockerlogo.png
  client/js/assets/icons/bikerack.png
  client/js/assets/icons/caution.png
  client/js/assets/icons/chevrons/down.png
  client/js/assets/icons/chevrons/left2.png
  client/js/assets/icons/chevrons/right2.png
  client/js/assets/icons/chevrons/up.png
  client/js/assets/icons/directions.png
  client/js/assets/icons/emptyavatar.png
  client/js/assets/icons/emptybikeavatar.png
  client/js/assets/icons/fillableavatar.png
  client/js/assets/icons/pins/0.png
  client/js/assets/icons/pins/1.png
  client/js/assets/icons/pins/2.png
  client/js/assets/icons/pins/3.png
  client/js/assets/icons/pins/4.png
  client/js/assets/icons/pins/5.png
  client/js/assets/icons/pins/Free.png
  client/js/assets/icons/pins/Paid.png
  client/js/assets/icons/pins/Translink.png
  client/js/assets/icons/review.png
  client/js/components/Loader/Loader.js
  client/js/components/Loader/index.js
  client/js/components/Loader/styles.js
  client/js/components/PhotoCarousel/PhotoCarousel.js
  client/js/components/PhotoCarousel/index.js
  client/js/components/PhotoCarousel/styles.js
  client/js/config/api.js
  client/js/navigation/RootStackNavigator.js
  client/js/screens/About/About.js
  client/js/screens/AuthWelcome/AuthWelcome.js
  client/js/screens/FindLocker/FindLocker.js
  client/js/screens/Locker/Locker.js
  client/js/screens/Locker/LockerContainer.js
  client/js/screens/Locker/styles.js
Labels: enhancement

#57 Am feature profile
  client/js/assets/images/profile_pic.jpg
  client/js/config/globalStyles.js
  client/js/screens/Profile/Profile.js
  client/js/screens/Profile/ProfileContainer.js
  client/js/screens/Profile/styles.js
Labels: enhancement

#69 add EditProfile screen to Profile Stack
  client/js/navigation/NavigationLayout.js
Labels: enhancement

#70 map markers showing and connected to review modal
  client/js/components/MapView/MapView.js
  client/js/screens/About/About.js
  client/js/screens/Locker/LockerContainer.js
Labels: enhancement

#77 Ja feature map view
  client/ios/Podfile.lock
  client/ios/bikelockerSpring2019/Images.xcassets/AppIcon.appiconset/Contents.json
  client/js/components/MapView/MapView.js
  client/js/components/MapView/styles.js
  client/js/screens/FindLocker/FindLocker.js
  client/js/screens/FindLocker/styles.js
  client/package.json
  client/yarn.lock
Labels: enhancement

#74 Ja feature about screen
  client/js/components/Search/Search.js
  client/js/components/Search/index.js
  client/js/components/Search/styles.js
  client/js/screens/About/About.js
  client/js/screens/About/styles.js
Labels: enhancement

#80 Js project dependencies
  client/android/app/build.gradle
  client/android/app/src/main/java/com/bikelockerspring2019/MainApplication.java
  client/android/settings.gradle
  client/ios/bikelockerSpring2019.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
Labels: enhancement

#84 Nc feature how to use screen
  client/js/assets/images/ComorImage.png
  client/js/assets/images/ComorImage@2x.png
  client/js/assets/images/Comorwbackground.png
  client/js/assets/images/Comorwbackground@2x.png
  client/js/assets/images/PinDiagram.png
  client/js/assets/images/PinDiagram2.png
  client/js/assets/images/pinDiagramWithLabel.png
  client/js/assets/images/pinDiagramWithLabel@2x.png
  client/js/screens/HowToUseApp/HowToUseApp.js
  client/js/screens/HowToUseApp/styles.js
Labels: enhancement

#76 Style the Edit Profile screen header
  client/js/screens/EditProfile/EditProfile.js
  client/js/screens/EditProfile/EditProfileContainer.js
  client/js/screens/EditProfile/styles.js
Labels: enhancement

#83 Ja feature onboarding
  .gitignore
  client/js/assets/images/biglockerlogo.png
  client/js/assets/images/comorimage.png
  client/js/assets/images/pindiagram.png
  client/js/assets/images/pindiagram@2.png
  client/js/screens/Contact/Contact.js
  client/js/screens/Contact/styles.js
  client/js/screens/Onboarding/Onboarding.js
  client/js/screens/Onboarding/OnboardingContainer.js
  client/js/screens/Onboarding/styles.js
  client/package.json
  client/yarn.lock
Labels: enhancement

#86 Ja feature map view
  client/js/components/MapView/MapView.js
Labels: enhancement

#88 Am feature edit profile
  client/js/components/EditProfileAbout/EditProfileAbout.js
  client/js/components/EditProfileAbout/styles.js
  client/js/screens/EditProfile/styles.js
Labels: enhancement

#93 Am feature edit profile
  client/js/assets/images/ComorImage.png
  client/js/assets/images/comorimage.png
  client/js/components/EditProfileAbout/EditProfileAbout.js
  client/js/components/EditProfileAbout/styles.js
  client/js/components/EditProfileContact/EditProfileContact.js
  client/js/components/EditProfileContact/styles.js
  client/js/screens/EditProfile/EditProfileContainer.js
Labels: bug

#94 Ja feature about screen
  client/android/app/build.gradle
  client/android/app/src/main/java/com/bikelockerspring2019/MainApplication.java
  client/android/settings.gradle
  client/ios/Podfile.lock
  client/js/screens/About/About.js
  client/js/screens/About/styles.js
  client/js/screens/Onboarding/Onboarding.js
Labels: enhancement

#96 Am feature edit profile
  client/ios/Podfile.lock
  client/js/assets/images/comorimage.png
  client/js/components/EditProfileAbout/EditProfileAbout.js
  client/js/components/EditProfileAbout/styles.js
  client/js/components/EditProfileContact/EditProfileContact.js
  client/js/components/EditProfileContact/styles.js
  client/js/screens/EditProfile/EditProfileContainer.js
Labels: bug

#97 Nc feature locker modal
  client/js/components/LockerRatingReadOnly/LockerRatingReadOnly.js
  client/js/components/LockerRatingReadOnly/index.js
  client/js/components/LockerRatingReadOnly/styles.js
  client/js/components/PhotoCarousel/PhotoCarousel.js
  client/js/helpers/avgRating.js
  client/js/navigation/RootStackNavigator.js
  client/js/screens/Locker/Locker.js
  client/js/screens/Locker/LockerContainer.js
  client/js/screens/Locker/styles.js
Labels: enhancement

#98 Am feature edit profile
  client/js/components/EditProfileAbout/EditProfileAbout.js
  client/js/components/EditProfileContact/EditProfileContact.js
  client/js/screens/EditProfile/EditProfile.js
  client/js/screens/EditProfile/EditProfileContainer.js
  client/js/screens/Profile/Profile.js
Labels: enhancement

#99 Am feature navigation
  client/js/navigation/NavigationLayout.js
Labels: enhancement

#95 Ja feature map view
  client/js/components/MapView/MapView.js
Labels: enhancement

#73 Nc feature auth
  client/ios/Podfile
  client/ios/Podfile.lock
  client/ios/bikelockerSpring2019.xcodeproj/project.pbxproj
  client/js/assets/images/image.png
  client/js/components/Loader/Loader.js
  client/js/components/Loader/styles.js
  client/js/config/globalStyles.js
  client/js/config/models.js
  client/js/helpers/validationLogin.js
  client/js/helpers/validationRegister.js
  client/js/navigation/NavigationLayout.js
  client/js/navigation/RootStackNavigator.js
  client/js/screens/AuthLoading/AuthLoading.js
  client/js/screens/AuthLoading/AuthLoadingContainer.js
  client/js/screens/AuthLoading/index.js
  client/js/screens/AuthLoading/styles.js
  client/js/screens/AuthWelcome/AuthWelcome.js
  client/js/screens/AuthWelcome/AuthWelcomeContainer.js
  client/js/screens/AuthWelcome/index.js
  client/js/screens/AuthWelcome/styles.js
  client/js/screens/Authentication/AuthenticationContainer.js
  client/js/screens/Authentication/index.js
  client/js/screens/Authentication/styles.js
  client/js/screens/FindLocker/FindLocker.js
  client/js/screens/FindLocker/FindLockerContainer.js
  client/js/screens/Login/Login.js
  client/js/screens/Login/LoginContainer.js
  client/js/screens/Login/index.js
  client/js/screens/Login/styles.js
  client/js/screens/Register/Register.js
  client/js/screens/Register/RegisterContainer.js
  client/js/screens/Register/index.js
  client/js/screens/Register/styles.js
  client/package.json
  client/yarn.lock
  server/src/email-password/signup.graphql
  server/src/email-password/signup.ts
  server/types.graphql
Labels: enhancement

#100 Ja feature global styles
  client/android/app/src/main/assets/fonts/Metropolis-ExtraBold.otf
  client/android/app/src/main/assets/fonts/Metropolis-Light.otf
  client/android/app/src/main/assets/fonts/OpenSans-Regular.ttf
  client/android/app/src/main/assets/fonts/OpenSans-SemiBold.ttf
  client/ios/bikelockerSpring2019.xcodeproj/project.pbxproj
  client/ios/bikelockerSpring2019/Info.plist
  client/js/assets/fonts/LICENSE.txt
  client/js/assets/fonts/Metropolis-ExtraBold.otf
  client/js/assets/fonts/Metropolis-Light.otf
  client/js/assets/fonts/OpenSans-Regular.ttf
  client/js/assets/fonts/OpenSans-SemiBold.ttf
  client/js/assets/fonts/SIL Open Font License.txt
  client/js/config/globalStyles.js
  client/js/screens/About/styles.js
  client/package.json
Labels: enhancement

#101 Nc feature resources
  client/js/screens/Resources/Resources.js
  client/js/screens/Resources/styles.js
Labels: enhancement

#102 Am feature edit profile
  client/js/components/EditProfileAbout/EditProfileAbout.js
  client/js/components/EditProfileContact/EditProfileContact.js
  client/js/screens/EditProfile/EditProfileContainer.js
  client/js/screens/Profile/ProfileContainer.js
Labels: enhancement

#107 Am feature profile
  client/js/screens/Profile/ProfileContainer.js
Labels: enhancement

#108 Am feature edit profile
  client/js/screens/EditProfile/EditProfileContainer.js
Labels: enhancement

#103 Gj feature add locker
  client/ios/bikelockerSpring2019.xcodeproj/project.pbxproj
  client/ios/bikelockerSpring2019/Base.lproj/LaunchScreen.xib
  client/js/components/GoogleMapSearch/styles.js
  client/js/components/LockerRating/LockerRating.js
  client/js/components/MapView/MapView.js
  client/js/navigation/NavigationLayout.js
  client/js/navigation/RootStackNavigator.js
  client/js/navigation/config.js
  client/js/screens/AddLocker/AddLocker.js
  client/js/screens/AddLocker/AddLockerContainer.js
  client/js/screens/AddLocker/index.js
  client/js/screens/AddLocker/styles.js
  client/js/screens/FindLocker/FindLockerContainer.js
  client/js/screens/FindLocker/index.js
Labels: enhancement

#111 Ja feature code cleanup
  client/android/app/build.gradle
  client/android/app/src/main/java/com/bikelockerspring2019/MainApplication.java
  client/android/settings.gradle
  client/ios/Podfile
  client/ios/Podfile.lock
  client/ios/bikelockerSpring2019.xcodeproj/project.pbxproj
  client/ios/bikelockerSpring2019/AppDelegate.m
  client/ios/bikelockerSpring2019/Base.lproj/LaunchScreen.xib
  client/ios/bikelockerSpring2019/Images.xcassets/Contents.json
  client/ios/bikelockerSpring2019/Images.xcassets/Splashscreen.imageset/Contents.json
  client/ios/bikelockerSpring2019/Images.xcassets/Splashscreen.imageset/image-1.png
  client/ios/bikelockerSpring2019/Images.xcassets/Splashscreen.imageset/image-2.png
  client/ios/bikelockerSpring2019/Images.xcassets/Splashscreen.imageset/image.png
  client/ios/bikelockerSpring2019/Info.plist
  client/js/App.js
  client/js/components/EditProfileAbout/EditProfileAbout.js
  client/js/components/EditProfileContact/EditProfileContact.js
  client/js/components/LockerRating/LockerRating.js
  client/js/components/LockerRatingReadOnly/LockerRatingReadOnly.js
  client/js/components/MapView/MapView.js
  client/js/components/PhotoCarousel/PhotoCarousel.js
  client/js/components/ThankYouModal/ThankYouModal.js
  client/js/screens/AddLocker/AddLocker.js
  client/js/screens/AddLocker/styles.js
  client/js/screens/EditProfile/EditProfile.js
  client/js/screens/EditProfile/EditProfileContainer.js
  client/js/screens/FindLocker/FindLocker.js
  client/js/screens/HowToUseApp/HowToUseApp.js
  client/js/screens/HowToUseApp/styles.js
  client/js/screens/Locker/Locker.js
  client/js/screens/Login/Login.js
  client/js/screens/Onboarding/Onboarding.js
  client/js/screens/Onboarding/styles.js
  client/js/screens/Profile/Profile.js
  client/js/screens/Register/Register.js
  client/package.json
  client/yarn.lock
Labels: enhancement

#109 Nc feature locker modal
  client/js/components/MapView/MapView.js
  client/js/navigation/NavigationLayout.js
  client/js/navigation/RootStackNavigator.js
  client/js/screens/Locker/Locker.js
  client/js/screens/Locker/styles.js
Labels: enhancement

#112 Create LICENSE
  LICENSE
Labels: documentation

#113 Ja feature loader styles
  client/ios/Podfile.lock
  client/js/components/GoogleMapSearch/styles.js
  client/js/components/Loader/Loader.js
  client/js/components/Loader/styles.js
Labels: enhancement

#114 Am feature edit profile
  client/js/components/EditProfileAbout/EditProfileAbout.js
  client/js/components/EditProfileContact/EditProfileContact.js
Labels: bug

#116 code cleanup and style consistency
  client/js/components/EditProfileAbout/styles.js
  client/js/components/EditProfileContact/styles.js
  client/js/components/GoogleMapSearch/GoogleMapsSearch.js
  client/js/components/Loader/styles.js
  client/js/components/LockerRatingReadOnly/styles.js
  client/js/components/MapView/styles.js
  client/js/components/ThankYouModal/styles.js
  client/js/screens/AddLocker/AddLockerContainer.js
  client/js/screens/AuthLoading/AuthLoadingContainer.js
  client/js/screens/AuthWelcome/styles.js
  client/js/screens/Contact/styles.js
  client/js/screens/EditProfile/EditProfile.js
  client/js/screens/EditProfile/styles.js
  client/js/screens/FindLocker/styles.js
  client/js/screens/HowToUseApp/styles.js
  client/js/screens/Locker/styles.js
  client/js/screens/Login/Login.js
  client/js/screens/Login/styles.js
  client/js/screens/Onboarding/styles.js
  client/js/screens/Register/Register.js
  client/js/screens/Register/styles.js
  client/js/screens/Resources/styles.js
  client/js/screens/Reviews/Reviews.js
  client/js/screens/Reviews/ReviewsContainer.js
  client/js/screens/Reviews/index.js
  client/js/screens/Reviews/styles.js
Labels: enhancement

#118 Gj feature reverse latlong
  client/js/screens/AddLocker/AddLocker.js
  client/js/screens/AddLocker/AddLockerContainer.js
  client/js/screens/AddLocker/styles.js
Labels: enhancement

#119 Am feature navigation
  client/ios/Podfile.lock
  client/js/navigation/NavigationLayout.js
Labels: enhancement

#121 Ja feature code cleaning
  client/index.js
  client/js/screens/Login/Login.js
  client/js/screens/Onboarding/Onboarding.js
  client/js/screens/Onboarding/styles.js
  client/js/screens/Register/Register.js
Labels: enhancement

#122 Am feature readme
  README.md
  demoGif/bikelocker_demo.gif
Labels: documentation

#123 Am feature profile
  client/js/screens/Profile/Profile.js
Labels: enhancement

#127 add image for app icon
  client/app.json
  client/ios/Podfile.lock
  client/ios/bikelockerSpring2019/Images.xcassets/AppIcon.appiconset/1024.png
  client/ios/bikelockerSpring2019/Images.xcassets/AppIcon.appiconset/120-1.png
  client/ios/bikelockerSpring2019/Images.xcassets/AppIcon.appiconset/120.png
  client/ios/bikelockerSpring2019/Images.xcassets/AppIcon.appiconset/180.png
  client/ios/bikelockerSpring2019/Images.xcassets/AppIcon.appiconset/40.png
  client/ios/bikelockerSpring2019/Images.xcassets/AppIcon.appiconset/58.png
  client/ios/bikelockerSpring2019/Images.xcassets/AppIcon.appiconset/60.png
  client/ios/bikelockerSpring2019/Images.xcassets/AppIcon.appiconset/80.png
  client/ios/bikelockerSpring2019/Images.xcassets/AppIcon.appiconset/87.png
  client/ios/bikelockerSpring2019/Images.xcassets/AppIcon.appiconset/Contents.json
  client/js/screens/Resources/styles.js
Labels: enhancement

#130 add refetch query to reviews
  client/js/screens/AddReview/AddReview.js
Labels: enhancement
